name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "backend.Tests/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "backend.Tests/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend

      - name: Build backend
        run: dotnet build --no-restore --configuration Release
        working-directory: ./backend

      - name: Restore test dependencies
        run: dotnet restore
        working-directory: ./backend.Tests

      - name: Build tests
        run: dotnet build --no-restore --configuration Release
        working-directory: ./backend.Tests

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx"
        working-directory: ./backend.Tests

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: backend.Tests/TestResults/test-results.trx

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Tests
          path: backend.Tests/TestResults/test-results.trx
          reporter: dotnet-trx
