name: Backend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore backend dependencies
        run: dotnet restore backend/backend.csproj

      - name: Restore test dependencies
        run: dotnet restore backend.Tests/backend.Tests.csproj

      - name: Build solution
        run: |
          dotnet build backend/backend.csproj --configuration Release --no-restore
          dotnet build backend.Tests/backend.Tests.csproj --configuration Release --no-restore

      - name: Run tests
        run: |
          dotnet test backend.Tests/backend.Tests.csproj \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --logger trx \
            --results-directory TestResults \
            --collect:"XPlat Code Coverage"

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Tests
          path: TestResults/**/*.trx
          reporter: dotnet-trx
